---
- name: Install moxie
  hosts: moxie
  sudo: true
  roles:
    - role: webservice
      name: "moxie"
      default: false
      upgrade: true
      websocket: true
      vhosts:
        - "moxie.pault.ag"
        - "moxie.lucifer.pault.ag"
        - "moxie.sunlightlabs.com"
    - role: daemon
      ports: ["0.0.0.0:2222:2222/tcp"]
      name: "moxie"
      # upgrade: true
      image: "paultag/moxie:latest"
      privileged: true
      environment_file: "moxie"
      command: "moxied"
      env: {
        "DATABASE_URL": "${DATABASE_URL}",
        "MOXIE_SOCKET": "${MOXIE_SOCKET}",
        "MOXIE_SLACKBOT_KEY": "${MOXIE_SLACKBOT_KEY}",
        "MOXIE_WEB_URL": "${MOXIE_WEB_URL}",
        "MOXIE_SMTP_HOST": "${MOXIE_SMTP_HOST}",
        "MOXIE_SMTP_USER": "${MOXIE_SMTP_USER}",
        "MOXIE_SMTP_PASS": "${MOXIE_SMTP_PASS}"
      }
      volumes: {
          "/run/docker.sock": "/run/docker.sock",
          "moxie": "/moxie/",
          "/srv/docker/nginx/serve/sockets/": "/sockets/"
      }
    # - role: daemon
    #   upgrade: true
    #   name: "moxied"
    #   image: "paultag/moxie:latest"
    #   privileged: true
    #   environment_file: "moxie"
    #   command: "moxied"
    #   env: {"DATABASE_URL": "${DATABASE_URL}"}
    #   volumes: {"/run/docker.sock": "/run/docker.sock"}
