---
- name: Install nginx
  hosts: machines
  sudo: true
  roles:
    - role: daemon
      name: "nginx"
      dirs: ["sites-enabled/",
             "serve/logs/",
             "serve/sockets/",
             "serve/sites/",]
      image: "paultag/nginx:latest"
      ports: ["0.0.0.0:80:80/tcp"]
      volumes: {"serve/": "/serve/",
                "sites-enabled/": "/etc/nginx/sites-enabled/"}
