---
- name: Install PostgreSQL
  hosts: lucifer
  sudo: true
  roles:
    - role: common-roles/daemon
      name: "postgres"
      image: "paultag/postgres:latest"
      command: "/usr/local/bin/paultag-psqld"
      volumes: {"9.4/main": "/var/lib/postgres/9.4/main/"}
