---
- name: Install rawdns
  hosts: lucifer
  sudo: true
  roles:
    - role: daemon
      files: ["rawdns.json"]
      name: "rawdns"
      image: "tianon/rawdns:latest"
      ports: ["172.17.42.1:53:53/udp"]
      volumes: {"rawdns.json": "/etc/rawdns.json",
                "/var/run/docker.sock": "/var/run/docker.sock"}
