---
- name: Install znc
  hosts: lucifer
  sudo: true
  roles:
    - role: daemon
      name: "znc"
      image: "paultag/znc:latest"  # Replace with Jess'
      command: "znc -f -r"
      ports: ["0.0.0.0:6697:6697/tcp"]
      volumes: {"znc": "/znc/.znc/"}
