---
 - name: Write out systemd unit file
   template: src=systemd.j2 dest=/etc/systemd/system/{{name}}.service owner=root group=root mode=0644
   notify: reload specs

 - name: Write out entrypoint
   template: src=entry.j2 dest=/usr/local/bin/{{name}} owner=root group=root mode=0755

 - name: 'Add in a {{name}} config directory.'
   file: path=/srv/docker/{{name}}/ state=directory

 - name: Set up {{name}} directories
   file: path=/srv/docker/{{name}}/{{item}}/ state=directory
   with_items: dirs

 - name: Copy in files
   copy: src={{name}}/files/{{item}} dest=/srv/docker/{{name}}/{{item}} owner=root group=root mode=0644
   with_items: files
   notify: restart {{name}}

 - name: Ensure docker-py is present on the host
   apt: name=python-docker update_cache=yes state=present

 - name: Update image
   dockimg: image={{image}} pulled=true state=present
   notify: 
       - stop {{name}}
       - remove {{name}}
       - upgrade {{name}}
       - start {{name}}

 - name: Ensure running
   service: name={{name}} state=started
