---
 - name: Write out nginx server config
   template: src=nginx.j2 dest=/srv/docker/nginx/sites-enabled/{{name}} owner=root group=root mode=0644
   notify: restart nginx

 - name: Check out website
   git: repo={{repo}} dest=/srv/docker/nginx/serve/sites/{{name}} update=yes accept_hostkey=yes
