---
 - name: Install Docker
   apt: name=docker.io update_cache=yes state=present
 
 - name: Starting Docker
   service: name=docker state=started
 
 - name: Add in a Docker config directory.
   file: path=/etc/docker/ state=directory

 - name: Configure docker
   copy: src=docker.sh dest=/etc/default/docker owner=root group=root mode=0644
   notify: restart docker
